#
# Frey Lint - Perform linting for ansible, yaml, and jinja on playbooks and roles
#

name: Ansible Lint

on:
  push:
    branches: [main, candidate]
    paths:
      - 'ansible-playbooks/playbooks/**'
      - 'ansible-playbooks/templates/**'
  pull_request:
    paths:
      - 'ansible-playbooks/playbooks/**'
      - 'ansible-playbooks/templates/**'

jobs:
  lint:
    runs-on: frey-infra-and-templates
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install linting tools
        run: pip install ansible-lint yamllint

      - name: Install ansible collections for netdevops
        run: ansible-galaxy collection install netbox.netbox:3.19.0 arista.eos:6.2.2 cisco.ios:5.3.0 cisco.iosxr:6.1.1 cisco.nxos:5.3.0 junipernetworks.junos:5.3.1 arista.avd ansible.utils
      
      - name: Run ansible-lint
        run: ansible-lint -x ignore-errors ansible-playbooks/playbooks/
      
      - name: Run yamllint
        run: |
            yamllint -d "{extends: default, rules: {line-length: disable}}" ansible-playbooks/playbooks/

      - name: Run jinja template validation
        run: |
            pip install j2cli
            find ansible-playbooks/templates/ -name "*.j2" -exec j2 {} \;

